# Generated by Django 4.2.2 on 2023-06-11 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeStampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField()),
                ("updated_on", models.DateTimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="customer.timestampmodel",
                    ),
                ),
                ("address_1", models.CharField(max_length=100)),
                ("address_2", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
            ],
            bases=("customer.timestampmodel",),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "timestampmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="customer.timestampmodel",
                    ),
                ),
                ("dba", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                (
                    "active",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("active", "Inactive"),
                            ("active", "Archived"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("arts entertainment", "Arts & Entertainment"),
                            ("construction", "Construction"),
                            ("education", "Education"),
                            ("energy", "Energy"),
                            ("food", "Food & Hospitality"),
                            ("finance", "Finance and Insurance"),
                            ("healthcare", "Healthcare"),
                            ("manufacturing", "Manufacturing"),
                            ("mining", "Mining"),
                            ("other", "Other Services"),
                            ("services", "Professional, Scientific, and Tech Services"),
                            ("real estate", "Real Estate"),
                            ("retail", "Retail"),
                            ("transportation", "Transportation & Logistics"),
                            ("utilities", "Utilities"),
                            ("wholesale", "Wholesale"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_billing_address",
                        to="customer.address",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_shipping_address",
                        to="customer.address",
                    ),
                ),
            ],
            bases=("customer.timestampmodel",),
        ),
    ]
