# Generated by Django 4.2.2 on 2023-06-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timestampmodel",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="timestampmodel",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
