# Generated by Django 4.2.2 on 2023-06-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_alter_timestampmodel_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
