# Generated by Django 4.2.2 on 2023-06-20 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_address_uuid_customer_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
