# Generated by Django 4.2.2 on 2023-07-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_alter_address_uuid_alter_customer_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="active",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                max_length=50,
            ),
        ),
    ]
