# Generated by Django 4.2.2 on 2023-07-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_address_address_2_alter_customer_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_1",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_2",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=20),
        ),
    ]
