# Generated by Django 4.2.2 on 2023-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_alter_address_address_1_alter_address_address_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
